project:
  type: default
  render:
    - template-computo-python.qmd
    #- README.qmd

title: "Optimal sub-Gaussian variance proxy for 3-mass distributions"
author:
  - name: Soufiane Atouani
    corresponding: true
    email: soufiane.atouani@inria.fr
    affiliations:
      - name: Université Grenoble Alpes, Inria, CNRS, Grenoble INP, LJK, 38000 Grenoble, France
        #department: Laboratoire Jean Kuntzmann
        url: https://www-ljk.imag.fr/
  - name: Olivier Marchal
    email: olivier.marchal@univ-st-etienne.fr
    url: https://math.univ-lyon1.fr/~marchal/index.html
    affiliations:
      - name: Université Jean Monnet Saint-Étienne, CNRS, Institut Camille Jordan UMR 5208
      - name: Institut Universitaire de France, Les Forges 2, 20 Rue du Dr Annino, 42000 Saint-Étienne, France
        #department: Institut Camille Jordan
        url: https://math.univ-lyon1.fr/icj/
  - name: Julyan Arbel 
    email: julyan.arbel@inria.fr
    url: https://www.julyanarbel.com/
    affiliations:
      - name: Université Grenoble Alpes, Inria, CNRS, Grenoble INP, LJK, 38000 Grenoble, France
        #department: Laboratoire Jean Kuntzmann
        url: https://www-ljk.imag.fr/
date: 17-01-2026
date-modified: last-modified
# description: |
#   Template for preparing a submission to Computo, using the [quarto journal extension](https://github.com/computorg/computo-quarto-extension), the Jupyter kernel (Python user) and the environment files to set-up the dependencies.

#   For a detailed, step-by-step guide on preparing your article, setting up the continuous integration and submitting it to Computo, please consult the [guidelines for authors](https://computo-journal.org/site/guidelines-authors.html).
abstract: >+
 We investigate the problem of characterizing the optimal variance proxy for sub-Gaussian random variables. We apply a general characterization method to discrete random variables with equally spaced atoms. We thoroughly study 3-mass distributions, thereby generalizing the well-studied Bernoulli case. We also prove that the discrete uniform distribution is strictly sub-Gaussian. Finally, we provide an open-source Python package that combines analytical and numerical approaches to compute optimal sub-Gaussian variance proxies across a wide range of distributions
keywords: [Sub-Gaussian property, discrete distributions, Uniform distribution]
bibliography: references.bib
github-user: satouani
repo: "Sub-Gaussian-Proxy-Variance-Library.git"
draft: false # set to false once the build is running
published: false # will be set to true once accepted
license: CC-BY-4.0
format:
  computo-html: default
  computo-pdf: default
          
        

jupyter: python3
